(package "async"
         "1.9.7"
         "Asynchronous processing in Emacs")

(website-url "https://github.com/jwiegley/emacs-async")
(keywords "async")

(package-file "async.el")

(files "async.el" "async-bytecomp.el" "*-async.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "nongnu")

(depends-on "emacs" "24.4")

(development
 (depends-on "buttercup"))
